begin;

alter table public.slates
  add column if not exists display_name text,
  add column if not exists external_event_id text,
  add column if not exists cut_penalty_per_round integer;

alter table public.slates
  drop constraint if exists slates_cut_penalty_per_round_check;

alter table public.slates
  add constraint slates_cut_penalty_per_round_check
  check (
    cut_penalty_per_round is null
    or cut_penalty_per_round >= 0
  );

create unique index if not exists slates_sport_external_event_id_unique
  on public.slates (sport, external_event_id)
  where external_event_id is not null;

create table if not exists public.golf_players (
  id bigint generated by default as identity primary key,
  espn_player_id text not null unique,
  display_name text not null,
  short_name text,
  country text,
  country_flag_url text,
  player_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.golf_event_players (
  id bigint generated by default as identity primary key,
  slate_id bigint not null
    references public.slates(id)
    on delete cascade,
  player_id bigint not null
    references public.golf_players(id)
    on delete cascade,

  leaderboard_order integer,
  official_score_to_par integer,
  official_score_display text,

  penalty_strokes integer not null default 0,
  fantasy_score integer,

  rounds_completed integer not null default 0,
  holes_completed integer not null default 0,
  current_round integer,
  last_hole integer,

  status text not null default 'active',
  tee_time timestamptz,
  tee_time_raw text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint golf_event_players_unique
    unique (slate_id, player_id),

  constraint golf_event_players_status_check
    check (
      status in (
        'scheduled',
        'active',
        'finished',
        'cut',
        'withdrawn',
        'disqualified',
        'did_not_start'
      )
    ),

  constraint golf_event_players_penalty_check
    check (penalty_strokes >= 0),

  constraint golf_event_players_rounds_completed_check
    check (rounds_completed between 0 and 10),

  constraint golf_event_players_holes_completed_check
    check (holes_completed between 0 and 180),

  constraint golf_event_players_current_round_check
    check (
      current_round is null
      or current_round between 1 and 10
    ),

  constraint golf_event_players_last_hole_check
    check (
      last_hole is null
      or last_hole between 1 and 18
    )
);

create index if not exists golf_event_players_slate_id_idx
  on public.golf_event_players (slate_id);

create index if not exists golf_event_players_player_id_idx
  on public.golf_event_players (player_id);

create index if not exists golf_event_players_leaderboard_idx
  on public.golf_event_players (slate_id, leaderboard_order);

create table if not exists public.golf_rounds (
  id bigint generated by default as identity primary key,
  event_player_id bigint not null
    references public.golf_event_players(id)
    on delete cascade,

  round_number integer not null,
  score_to_par integer,
  score_display text,
  strokes integer,
  holes_completed integer not null default 0,
  tee_time timestamptz,
  tee_time_raw text,
  status text not null default 'scheduled',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint golf_rounds_unique
    unique (event_player_id, round_number),

  constraint golf_rounds_round_number_check
    check (round_number between 1 and 10),

  constraint golf_rounds_holes_completed_check
    check (holes_completed between 0 and 18),

  constraint golf_rounds_status_check
    check (
      status in (
        'scheduled',
        'active',
        'finished',
        'not_played'
      )
    )
);

create index if not exists golf_rounds_event_player_id_idx
  on public.golf_rounds (event_player_id);

create table if not exists public.golf_holes (
  id bigint generated by default as identity primary key,
  round_id bigint not null
    references public.golf_rounds(id)
    on delete cascade,

  hole_number integer not null,
  strokes integer,
  relative_to_par integer,
  score_display text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint golf_holes_unique
    unique (round_id, hole_number),

  constraint golf_holes_hole_number_check
    check (hole_number between 1 and 18),

  constraint golf_holes_strokes_check
    check (
      strokes is null
      or strokes between 1 and 20
    )
);

create index if not exists golf_holes_round_id_idx
  on public.golf_holes (round_id);

alter table public.golf_players enable row level security;
alter table public.golf_event_players enable row level security;
alter table public.golf_rounds enable row level security;
alter table public.golf_holes enable row level security;

commit;
