"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import AppNav from "@/components/AppNav";
import type { NbaLiveGame } from "@/lib/providers/nbaLiveScores";
import { easternToday, nbaDateKey, shiftNbaDate } from "@/lib/live-scores/nbaDate";
import NbaGameCenterModal from "./NbaGameCenterModal";

const line = (game: NbaLiveGame) => { const odds = game.odds; if (!odds) return null; const favorite = odds.favoriteTeamId === game.awayTeam.id ? game.awayTeam.abbreviation : odds.favoriteTeamId === game.homeTeam.id ? game.homeTeam.abbreviation : null; return [favorite && odds.spread !== null ? `${favorite} ${odds.spread}` : "", odds.overUnder !== null ? `O/U ${odds.overUnder}` : ""].filter(Boolean).join(" · ") || null; };

export default function NbaLiveScores() {
  const [selectedDate, setSelectedDate] = useState(easternToday); const [games, setGames] = useState<NbaLiveGame[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(""); const [selectedGame, setSelectedGame] = useState<NbaLiveGame | null>(null);
  const load = useCallback(async (manual = false) => { const date = nbaDateKey(selectedDate); if (!date) return; manual ? setRefreshing(true) : setLoading(true); setError(""); try { const response = await fetch(`/api/live-scores/nba/scores?date=${date}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load NBA scores."); setGames(data.games ?? []); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load NBA scores."); } finally { setLoading(false); setRefreshing(false); } }, [selectedDate]);
  useEffect(() => { void load(); }, [load]);
  const hasLive = games.some((game) => game.status === "in"); useEffect(() => { if (!hasLive) return; const interval = window.setInterval(() => void load(true), 30000); return () => window.clearInterval(interval); }, [hasLive, load]);
  useEffect(() => { const refreshOnFocus = () => { if (document.visibilityState === "visible") void load(true); }; document.addEventListener("visibilitychange", refreshOnFocus); return () => document.removeEventListener("visibilitychange", refreshOnFocus); }, [load]);
  const ordered = useMemo(() => [...games].sort((a, b) => ({ in: 0, pre: 1, post: 2 }[a.status] ?? 1) - ({ in: 0, pre: 1, post: 2 }[b.status] ?? 1) || Date.parse(a.startAt) - Date.parse(b.startAt)), [games]);
  const move = (days: number) => setSelectedDate((current) => shiftNbaDate(current, days) ?? current);
  return <main className="min-h-screen bg-slate-50 px-3 py-5 pb-24 text-slate-900 sm:px-4 sm:py-6 sm:pb-6"><div className="mx-auto max-w-5xl space-y-4"><AppNav /><section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-sky-600">NBA</p><h1 className="mt-1 text-2xl font-black tracking-tight">Live</h1><p className="mt-1 text-sm text-slate-500">Real-world NBA scores, game action, and box scores.</p></div><button type="button" onClick={() => void load(true)} disabled={refreshing} className="text-xl text-slate-500 disabled:opacity-40" aria-label="Refresh NBA scores">↻</button></div><div className="mt-4 flex items-center justify-between rounded-xl bg-slate-50 p-1"><button type="button" onClick={() => move(-1)} className="rounded-lg px-3 py-2 text-sm font-bold text-slate-600" aria-label="Previous day">←</button><input type="date" aria-label="NBA schedule date" value={selectedDate} onChange={(event) => setSelectedDate(event.target.value)} className="min-w-0 bg-transparent px-2 py-2 text-center text-sm font-black text-slate-800" /><button type="button" onClick={() => move(1)} className="rounded-lg px-3 py-2 text-sm font-bold text-slate-600" aria-label="Next day">→</button></div></section>{loading ? <p className="py-8 text-center text-sm text-slate-500">Loading NBA games…</p> : error ? <p className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</p> : ordered.length ? <section className="space-y-2">{ordered.map((game) => <GameCard key={game.espnEventId} game={game} onClick={() => setSelectedGame(game)} />)}</section> : <p className="rounded-xl border border-slate-200 bg-white p-6 text-center text-sm text-slate-500">No NBA games scheduled for this date.</p>}</div>{selectedGame ? <NbaGameCenterModal game={selectedGame} onClose={() => setSelectedGame(null)} /> : null}</main>;
}
function GameCard({ game, onClick }: { game: NbaLiveGame; onClick: () => void }) { const started = game.status !== "pre"; return <button type="button" onClick={onClick} className={`w-full rounded-xl border bg-white px-3 py-2.5 text-left shadow-sm ${game.status === "in" ? "border-sky-400 ring-1 ring-sky-400/20" : "border-slate-200"}`}><TeamRow team={game.awayTeam} started={started} /><TeamRow team={game.homeTeam} started={started} /><div className="mt-2 flex justify-between gap-3 border-t border-slate-100 pt-2 text-[11px]"><span className={game.status === "in" ? "font-black text-sky-600" : "font-semibold text-slate-500"}>{game.status === "pre" ? new Date(game.startAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }) : game.statusDetail || (game.completed ? "Final" : "Live")}{game.broadcast?.network ? ` · ${game.broadcast.network}` : ""}</span>{line(game) ? <span className="text-right text-slate-500">{line(game)}</span> : null}</div></button>; }
function TeamRow({ team, started }: { team: NbaLiveGame["awayTeam"]; started: boolean }) { return <div className="flex items-center gap-2 py-0.5"><div className="flex h-7 w-7 items-center justify-center">{team.logo ? <img src={team.logo} alt="" className="max-h-7 max-w-7 object-contain" /> : null}</div><div className="min-w-0 flex-1"><p className={`truncate text-sm ${team.winner ? "font-black" : "font-bold"}`}>{team.displayName}</p>{team.record ? <p className="text-[11px] text-slate-500">{team.record}</p> : null}</div>{started ? <span className={`w-9 text-right text-lg tabular-nums ${team.winner ? "font-black" : "font-bold text-slate-600"}`}>{team.score ?? "—"}</span> : null}</div>; }
