"use client";

import { useEffect, useRef, useState } from "react";
import { nbaFullCourtMarker, nbaPeriodLabel, nbaPlayAttackIndicator, type NbaPlay, type NbaShotMarker } from "@/lib/live-scores/nbaPlays";

const CourtEnd = ({ side }: { side: "left" | "right" }) => {
  const left = side === "left", hoopX = left ? 5.25 : 88.75, boardX = left ? 4 : 90, laneX = left ? 0 : 75, freeThrowX = left ? 19 : 75;
  const arc = left ? "M 0 3 L 14 3 M 0 47 L 14 47 M 14 3 A 23.75 23.75 0 0 1 14 47" : "M 94 3 L 80 3 M 94 47 L 80 47 M 80 3 A 23.75 23.75 0 0 0 80 47";
  return <g fill="none" stroke="currentColor" strokeWidth="0.55"><rect x={laneX} y="17" width="19" height="16" /><line x1={freeThrowX} y1="17" x2={freeThrowX} y2="33" /><path d={left ? "M 19 17 A 8 8 0 0 0 19 33" : "M 75 17 A 8 8 0 0 1 75 33"} strokeDasharray="1.3 1.3" /><path d={left ? `M ${hoopX} 21 A 4 4 0 0 0 ${hoopX} 29` : `M ${hoopX} 21 A 4 4 0 0 1 ${hoopX} 29`} /><path d={arc} /><line x1={boardX} y1="22" x2={boardX} y2="28" strokeWidth="0.9" /><circle cx={hoopX} cy="25" r="0.75" strokeWidth="0.8" /></g>;
};

type Replay = { progress: number; active: boolean; result: boolean };
const idleReplay: Replay = { progress: 0, active: false, result: false };
function ballPoint(marker: NbaShotMarker, progress: number) { const hoopX = marker.basket === "left" ? 5.25 : 88.75, direction = marker.basket === "left" ? -1 : 1, travelEnd = marker.made ? hoopX + direction * 1.1 : hoopX - direction * 2.25, t = Math.min(progress / 0.84, 1); if (progress > 0.84) return { x: hoopX + (travelEnd - hoopX) * ((progress - 0.84) / 0.16), y: 25 }; const controlY = Math.max(2, marker.top - Math.max(5, Math.min(14, Math.abs(marker.left - hoopX) * 0.28))); return { x: (1 - t) ** 2 * marker.left + 2 * (1 - t) * t * ((marker.left + hoopX) / 2) + t ** 2 * hoopX, y: (1 - t) ** 2 * marker.top + 2 * (1 - t) * t * controlY + t ** 2 * 25 }; }
function ShotReplay({ marker, playId, reducedMotion, replayEnabled }: { marker: NbaShotMarker; playId: string; reducedMotion: boolean; replayEnabled: boolean }) { const [replay, setReplay] = useState<Replay>(idleReplay), frame = useRef<number | null>(null), settle = useRef<number | null>(null); useEffect(() => { if (frame.current) cancelAnimationFrame(frame.current); if (settle.current) window.clearTimeout(settle.current); if (reducedMotion || !replayEnabled) { setReplay(idleReplay); return; } const started = performance.now(), duration = 900; const tick = (now: number) => { const progress = Math.min((now - started) / duration, 1); setReplay({ progress, active: true, result: progress >= 0.84 }); if (progress < 1) frame.current = requestAnimationFrame(tick); else settle.current = window.setTimeout(() => setReplay(idleReplay), 220); }; frame.current = requestAnimationFrame(tick); return () => { if (frame.current) cancelAnimationFrame(frame.current); if (settle.current) window.clearTimeout(settle.current); }; }, [playId, reducedMotion, replayEnabled]); const hoopX = marker.basket === "left" ? 5.25 : 88.75, ball = ballPoint(marker, replay.progress); return <g><g transform={`translate(${marker.left} ${marker.top})`}><circle r="1.45" fill="white" className={marker.made ? "stroke-emerald-600" : "stroke-rose-600"} strokeWidth="0.8" /><circle r="0.48" className={marker.made ? "fill-emerald-500" : "fill-rose-500"} /></g>{replay.active ? <circle cx={ball.x} cy={ball.y} r="1.05" fill="#d97706" stroke="#78350f" strokeWidth="0.35" /> : null}{replay.result && marker.made ? <circle cx={hoopX} cy="25" r="2" fill="none" className="stroke-emerald-500" strokeWidth="0.7" /> : null}{replay.result && !marker.made ? <path d={`M ${hoopX - 1.35} 23.65 L ${hoopX + 1.35} 26.35 M ${hoopX + 1.35} 23.65 L ${hoopX - 1.35} 26.35`} className="stroke-rose-700" strokeWidth="0.65" /> : null}</g>; }

export default function NbaPlayCourt({ play, awayTeamId, homeTeamId, awayTeamAbbreviation, homeTeamAbbreviation, compact = false, replayEnabled = true }: { play: NbaPlay | null; awayTeamId?: string; homeTeamId?: string; awayTeamAbbreviation?: string | null; homeTeamAbbreviation?: string | null; compact?: boolean; replayEnabled?: boolean }) { const marker = play ? nbaFullCourtMarker(play, { awayTeamId, homeTeamId }) : null; const attackIndicator = nbaPlayAttackIndicator(play, { awayTeamId, homeTeamId, awayTeamAbbreviation, homeTeamAbbreviation }); const [reducedMotion, setReducedMotion] = useState(false); useEffect(() => { const media = window.matchMedia("(prefers-reduced-motion: reduce)"), update = () => setReducedMotion(media.matches); update(); media.addEventListener("change", update); return () => media.removeEventListener("change", update); }, []); if (compact) return <section className="rounded-xl border border-slate-700 bg-slate-950/80 px-2 py-1.5 shadow-sm shadow-slate-950/40 backdrop-blur" aria-label="Compact selected play court"><div className="flex min-w-0 items-center gap-1 px-1 text-[10px] font-bold text-slate-100">{play ? <><span className="shrink-0">{nbaPeriodLabel(play.period)}{play.clock ? ` · ${play.clock}` : ""}</span>{attackIndicator ? <span className="shrink-0 text-slate-300">· {attackIndicator}</span> : null}<span className="truncate">· {play.text}</span></> : "Selected play"}</div><svg viewBox="0 0 94 50" className="mx-auto mt-1 block w-full max-w-[260px] rounded border border-amber-800 bg-amber-50 text-amber-800" role="img" aria-label="Compact regulation NBA court"><rect x="0.35" y="0.35" width="93.3" height="49.3" fill="none" stroke="currentColor" strokeWidth="0.7" /><line x1="47" y1="0" x2="47" y2="50" stroke="currentColor" strokeWidth="0.55" /><circle cx="47" cy="25" r="6" fill="none" stroke="currentColor" strokeWidth="0.55" /><CourtEnd side="left" /><CourtEnd side="right" />{marker && play ? <ShotReplay marker={marker} playId={play.id} reducedMotion={reducedMotion} replayEnabled={replayEnabled} /> : null}</svg></section>;
  return <section className="rounded-xl border border-slate-200 bg-slate-50 p-3" aria-label="Selected play court"><div className="mb-2 grid grid-cols-[1fr_auto_1fr] items-center gap-2"><h2 className="text-xs font-black uppercase tracking-wider text-slate-500">Selected play</h2><span className="text-[10px] font-bold text-slate-500">{attackIndicator}</span>{play ? <span className="text-right text-[10px] font-bold text-slate-500">{nbaPeriodLabel(play.period)}{play.clock ? ` · ${play.clock}` : ""}</span> : null}</div><svg viewBox="0 0 94 50" className="block w-full rounded-lg border border-amber-800 bg-amber-50 text-amber-800" role="img" aria-label="Regulation NBA court, 94 by 50 foot proportions"><rect x="0.35" y="0.35" width="93.3" height="49.3" fill="none" stroke="currentColor" strokeWidth="0.7" /><line x1="47" y1="0" x2="47" y2="50" stroke="currentColor" strokeWidth="0.55" /><circle cx="47" cy="25" r="6" fill="none" stroke="currentColor" strokeWidth="0.55" /><CourtEnd side="left" /><CourtEnd side="right" />{marker && play ? <ShotReplay marker={marker} playId={play.id} reducedMotion={reducedMotion} replayEnabled={replayEnabled} /> : null}</svg><div className="mt-2 rounded-lg bg-white px-2.5 py-2 text-xs text-slate-700">{play ? <><p className={play.scoringPlay ? "font-bold text-slate-900" : "font-medium text-slate-800"}>{play.text}</p><p className="mt-1 text-slate-500">{play.awayScore !== null && play.homeScore !== null ? `${play.awayScore}-${play.homeScore}` : "Score unavailable"}{marker ? ` · ${marker.made ? "Made" : "Missed"} shot` : ""}</p></> : <p className="text-slate-500">Select a play to inspect it on the court.</p>}</div></section>; }
