/* eslint-disable @typescript-eslint/no-require-imports */
const assert=require('node:assert/strict'),test=require('node:test'),fs=require('node:fs'),ts=require('typescript'),Module=require('node:module'),path=require('node:path');
const resolve=Module._resolveFilename;Module._resolveFilename=function(request,parent,...rest){return request.startsWith('@/')?resolve(path.join(process.cwd(),request.slice(2)),parent,...rest):resolve(request,parent,...rest)};
require.extensions['.ts']=(module,filename)=>module._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true},fileName:filename}).outputText,filename);
const {NFL_PROJECTION_V2,selectNflAsOfObservationVersions,projectNflV2O1Raw,nflProjectionCacheRecord,scoreCachedNflProjection,validateNflRawProjectionStats}=require('../lib/analytics/nfl/projectionInfrastructure.ts');
const {generateNflProjectionStatCache}=require('../lib/analytics/nfl/projectionGeneration.server.ts');
function row({id=1,player=7,provider='42',event='100',position='RB',day=1,knownDay=2,season=2026,attempts=10,yards=20}={}){return {id,provider:'espn',provider_player_id:provider,provider_event_id:event,local_player_id:player,position,season,week:day,phase:'regular',game_at:`2026-09-${String(day).padStart(2,'0')}T17:00:00Z`,known_at:`2026-09-${String(knownDay).padStart(2,'0')}T17:00:00Z`,completions:position==='QB'?20:null,passing_attempts:position==='QB'?30:null,passing_yards:position==='QB'?240:null,passing_touchdowns:position==='QB'?2:null,interceptions:position==='QB'?1:null,rushing_attempts:attempts,rushing_yards:yards,rushing_touchdowns:0,receiving_targets:position==='QB'?null:4,receptions:position==='QB'?null:2,receiving_yards:position==='QB'?null:16,receiving_touchdowns:0,fumbles_lost:0}}
test('strict as-of selection uses versions, not later corrections or future games',()=>{const rows=[row({id:1,event:'a',day:1,knownDay:2,yards:20}),row({id:2,event:'a',day:1,knownDay:8,yards:99}),row({id:3,event:'future',day:9,knownDay:9,yards:999}),row({id:4,event:'late-known',day:2,knownDay:8,yards:999})];const before=selectNflAsOfObservationVersions({rows,playerId:7,targetSeason:2026,asOf:'2026-09-05T00:00:00Z'});assert.deepEqual(before.map(x=>[x.provider_event_id,x.rushing_yards]),[['a',20]]);const after=selectNflAsOfObservationVersions({rows,playerId:7,targetSeason:2026,asOf:'2026-09-10T00:00:00Z'});assert.deepEqual(after.map(x=>[x.provider_event_id,x.rushing_yards]),[['a',99],['late-known',999],['future',999]]);});
test('frozen O1 uses last-five opportunity, last-eight ratio totals, and confidence thresholds',()=>{const rows=Array.from({length:8},(_,i)=>row({id:i+1,event:String(i+1),day:i+1,knownDay:i+1,attempts:i<3?1:10,yards:(i<3?1:10)*2}));const low=projectNflV2O1Raw({playerId:7,providerPlayerId:'42',position:'RB',season:2026,asOf:'2026-09-20T00:00:00Z',history:rows.slice(0,4)}),normal=projectNflV2O1Raw({playerId:7,providerPlayerId:'42',position:'RB',season:2026,asOf:'2026-09-20T00:00:00Z',history:rows});assert.equal(NFL_PROJECTION_V2,'nfl-v2-o1-opportunity5-production8-coldstart-v2');assert.equal(low.confidence,'low');assert.equal(normal.confidence,'normal');assert.equal(normal.components.rushing_attempts,10);assert.equal(normal.projectedStats.rushing_yards,20);assert.equal(normal.sample.opportunity_window_games,5);assert.equal(normal.sample.production_window_games,8);assert.equal(projectNflV2O1Raw({playerId:7,providerPlayerId:'42',position:'RB',season:2026,asOf:'2026-09-20T00:00:00Z',history:[]}),null);});
test('generator abstains for zero history and cache identity is raw-only/idempotent',async()=>{const rows=[row()];const writes=[];const result=await generateNflProjectionStatCache({players:[{localPlayerId:7,providerPlayerId:'42',position:'RB'},{localPlayerId:8,providerPlayerId:'43',position:'WR'}],targetSeason:2026,asOf:'2026-09-20T00:00:00Z',repository:{loadHistories:async()=>new Map([[7,rows],[8,[]]]),appendStatCache:async x=>writes.push(...x)}});assert.equal(result.cached,1);assert.deepEqual(result.unavailable,[{playerId:8,reason:'zero_current_or_prior_season_history'}]);const cache=writes[0];assert.ok(validateNflRawProjectionStats(cache.projected_stats));assert.equal(cache.group_id,undefined);assert.equal(cache.slate_id,undefined);assert.equal(cache.fantasy_points,undefined);assert.match(cache.projection_hash,/^[a-f0-9]{64}$/);});
test('one cached raw stat line scores differently under two frozen NFL snapshots without cache mutation',()=>{const projection=projectNflV2O1Raw({playerId:7,providerPlayerId:'42',position:'RB',season:2026,asOf:'2026-09-20T00:00:00Z',history:[row()]}),cache=nflProjectionCacheRecord({playerId:7,providerPlayerId:'42',position:'RB',season:2026,asOf:'2026-09-20T00:00:00Z',generatedAt:'2026-09-20T00:01:00Z',projection});const original=structuredClone(cache.projected_stats);const a=scoreCachedNflProjection(cache,{sport:'nfl',scoring:{rushingYards:.1}}),b=scoreCachedNflProjection(cache,{sport:'nfl',scoring:{rushingYards:.2}});assert.notEqual(a,b);assert.deepEqual(cache.projected_stats,original);});
test('migration is raw-only append-only service-role cache and repository pages version history',()=>{const sql=fs.readFileSync('supabase/migrations/20260927000100_nfl_projection_stat_cache.sql','utf8'),repo=fs.readFileSync('lib/analytics/nfl/observationRepository.server.ts','utf8');assert.match(sql,/create table public\.nfl_projection_stat_cache_versions/);assert.match(sql,/create view public\.nfl_projection_stat_cache/);assert.match(sql,/before update or delete/);assert.match(sql,/enable row level security/);assert.match(sql,/grant select, insert on public\.nfl_projection_stat_cache_versions to service_role/);assert.match(sql,/not \(projected_stats \?\| array\['fantasy_points','group_id','league_id','slate_id'\]\)/);assert.match(repo,/const HISTORY_PLAYER_BATCH_SIZE = 200;/);assert.match(repo,/\.lt\("known_at", input\.asOf\)/);assert.match(repo,/\.range\(from, from \+ PAGE_SIZE - 1\)/);});
