/* eslint-disable @typescript-eslint/no-require-imports */
const assert=require('node:assert/strict'),test=require('node:test'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(module,filename)=>module._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022},fileName:filename}).outputText,filename);
const {canonicalNflObservationHashPayload,hashNflObservation}=require('../lib/analytics/nfl/observationFoundation.ts');
function row(overrides={}){return {provider:'espn',providerPlayerId:'3046779',providerEventId:'401772835',localPlayerId:80,position:'QB',season:2026,week:2,phase:'regular',gameAt:'2026-09-14T17:00:00.000Z',completedAt:null,team:{providerId:'8',abbreviation:'DET'},opponent:{providerId:'3',abbreviation:'CHI'},homeAway:'home',stats:{completions:20,passingAttempts:31,passingYards:250,passingTouchdowns:2,interceptions:1,rushingAttempts:3,rushingYards:8,rushingTouchdowns:0,receivingTargets:null,receptions:null,receivingYards:null,receivingTouchdowns:null,fumblesLost:0},provenance:{gameLogSourceUrl:'https://espn.test/log',gameLogFetchedAt:'2026-09-15T03:00:00Z',fumbleSummarySourceUrl:'https://espn.test/summary',fumbleSummaryFetchedAt:'2026-09-15T03:01:00Z',knownAt:'2026-09-15T03:02:00Z',normalizationVersion:'espn_nfl_gamelog_fumbles_v1'},...overrides};}
test('NFL factual hash is deterministic and canonicalizes stat key insertion order',()=>{const a=row(),b=row({stats:{fumblesLost:0,receivingTouchdowns:null,receivingYards:null,receptions:null,receivingTargets:null,rushingTouchdowns:0,rushingYards:8,rushingAttempts:3,interceptions:1,passingTouchdowns:2,passingYards:250,passingAttempts:31,completions:20}});assert.deepEqual(canonicalNflObservationHashPayload(a),canonicalNflObservationHashPayload(b));assert.equal(hashNflObservation(a),hashNflObservation(b));});
test('volatile provenance timestamps do not change factual content identity',()=>{const a=row(),b=row({provenance:{...a.provenance,gameLogFetchedAt:'2026-09-16T03:00:00Z',fumbleSummaryFetchedAt:'2026-09-16T03:01:00Z',knownAt:'2026-09-16T03:02:00Z'}});assert.equal(hashNflObservation(a),hashNflObservation(b));});
test('factual correction, player/event binding, and normalization version create distinct hashes',()=>{const a=row();assert.notEqual(hashNflObservation(a),hashNflObservation({...a,stats:{...a.stats,passingYards:251}}));assert.notEqual(hashNflObservation(a),hashNflObservation({...a,providerPlayerId:'3046778'}));assert.notEqual(hashNflObservation(a),hashNflObservation({...a,providerEventId:'401772836'}));assert.notEqual(hashNflObservation(a),hashNflObservation({...a,localPlayerId:81}));assert.notEqual(hashNflObservation(a),hashNflObservation({...a,provenance:{...a.provenance,normalizationVersion:'v2'}}));});
test('factual zeros and QB/non-QB fumble provenance are representable',()=>{const qb=row({stats:{...row().stats,fumblesLost:0}});assert.equal(canonicalNflObservationHashPayload(qb).stats.fumblesLost,0);const receiver=row({position:'WR',stats:{...row().stats,passingAttempts:null,passingYards:null,passingTouchdowns:null,interceptions:null,fumblesLost:0},provenance:{...row().provenance,fumbleSummarySourceUrl:null,fumbleSummaryFetchedAt:null}});assert.equal(canonicalNflObservationHashPayload(receiver).stats.fumblesLost,0);assert.equal(receiver.provenance.fumbleSummarySourceUrl,null);});
test('migration is factual-only, immutable, deduplicated, and service-role-only',()=>{const sql=fs.readFileSync('supabase/migrations/20260926000100_nfl_projection_observation_foundation.sql','utf8');assert.match(sql,/create table public\.nfl_player_game_observation_versions/);assert.match(sql,/references public\.players_nfl\(id\)/);assert.match(sql,/unique \(provider, provider_player_id, provider_event_id, observation_hash\)/);assert.match(sql,/create view public\.nfl_player_game_observations/);assert.match(sql,/before update or delete/);assert.match(sql,/enable row level security/);assert.match(sql,/grant select, insert on public\.nfl_player_game_observation_versions to service_role/);assert.doesNotMatch(sql,/nfl_projection_stat_cache/);});
