/* eslint-disable @typescript-eslint/no-require-imports */
const assert=require('node:assert/strict'),test=require('node:test'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(module,filename)=>module._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022},fileName:filename}).outputText,filename);
const {NFL_RESEARCH_SCORING_V1,actualNflResearchStats,scoreNflResearch,projectNflResearch}=require('../lib/analytics/nfl/researchCandidates.ts');
function row(n,season=2024,position='RB',stats={}){return {providerPlayerId:'1',position,season,eventId:String(n),week:n,gameAt:`${season}-09-${String(n).padStart(2,'0')}T18:00:00Z`,stats:{passingAttempts:0,passingYards:0,passingTouchdowns:0,interceptions:0,rushingAttempts:10,rushingYards:50,rushingTouchdowns:0,receivingTargets:4,receptions:3,receivingYards:30,receivingTouchdowns:0,fumblesLost:0,...stats}}}
test('research scoring reconstructs the canonical frozen 111 NFL snapshot',()=>{const stats={passingYards:250,passingTouchdowns:2,interceptions:1,rushingYards:10,rushingTouchdowns:1,receivingYards:20,receivingTouchdowns:1,receptions:2,fumblesLost:1};assert.equal(scoreNflResearch(stats),10+8-2+1+6+2+6+2-2);assert.equal(NFL_RESEARCH_SCORING_V1.receptions,1);assert.equal(actualNflResearchStats(row(1)).rushingYards,50);});
test('no history abstains and target/future rows cannot affect a chronological projection',()=>{const target=row(5),past=[row(1),row(2),row(3),row(4)],a=projectNflResearch('nfl-v2-o1-opportunity5-production8-v1',target,past),b=projectNflResearch('nfl-v2-o1-opportunity5-production8-v1',target,[...past,row(6,2024,'RB',{rushingYards:9999})]);assert.equal(projectNflResearch('nfl-v2-o1-opportunity5-production8-v1',target,[]),null);assert.deepEqual(a,b);});
test('opportunity adapters and ratio-of-totals use factual denominators',()=>{const history=[row(1,2024,'WR',{receivingTargets:10,receptions:5,receivingYards:100,rushingAttempts:0}),row(2,2024,'WR',{receivingTargets:2,receptions:2,receivingYards:10,rushingAttempts:0})],target=row(3,2024,'WR');const p=projectNflResearch('nfl-v2-o1-opportunity5-production8-v1',target,history);assert.equal(p.components.opportunity.receivingTargets,6);assert.equal(p.projectedStats.receptions,6*7/12);assert.equal(p.projectedStats.receivingYards,6*110/12);});
test('O2 downweights an isolated low opportunity but repeated low opportunity remains evidence',()=>{const normal=Array.from({length:5},(_,i)=>row(i+1,2024,'RB',{rushingAttempts:10})),low=row(6,2024,'RB',{rushingAttempts:1}),target=row(7,2024,'RB');const o1=projectNflResearch('nfl-v2-o1-opportunity5-production8-v1',target,[...normal,low]),o2=projectNflResearch('nfl-v2-o2-robust-opportunity6-production10-v1',target,[...normal,low]);assert.equal(o2.components.downweighted,1);assert.ok(o2.components.opportunity.rushingAttempts>o1.components.opportunity.rushingAttempts);const repeated=[...normal,row(6,2024,'RB',{rushingAttempts:1}),row(7,2024,'RB',{rushingAttempts:1}),row(8,2024,'RB',{rushingAttempts:1})];assert.ok(projectNflResearch('nfl-v2-o2-robust-opportunity6-production10-v1',row(9,2024,'RB'),repeated).components.opportunity.rushingAttempts<8);});
test('O3 admits exactly one immediate prior-season game before three current games',()=>{const previous=[row(1,2023,'TE',{receivingTargets:8})],target=row(1,2024,'TE'),o2=projectNflResearch('nfl-v2-o2-robust-opportunity6-production10-v1',target,previous),o3=projectNflResearch('nfl-v2-o3-robust-opportunity6-production10-prior1game-v1',target,previous);assert.equal(o2,null);assert.equal(o3.components.admitted.length,1);const current=[row(1,2024,'TE'),row(2,2024,'TE'),row(3,2024,'TE')];assert.ok(projectNflResearch('nfl-v2-o3-robust-opportunity6-production10-prior1game-v1',row(4,2024,'TE'),[...previous,...current]).components.admitted.every(x=>x.season===2024));});
test('zero production denominators are deterministic rather than fabricated',()=>{const history=[row(1,2024,'RB',{receivingTargets:0,receptions:0,receivingYards:0,rushingAttempts:0,rushingYards:0})],p=projectNflResearch('nfl-v2-o1-opportunity5-production8-v1',row(2,2024,'RB'),history);assert.equal(p.projectedStats.receivingYards,0);assert.equal(p.projectedStats.rushingYards,0);});
test('candidate output is deterministic',()=>{const history=[row(1),row(2),row(3)],target=row(4);assert.deepEqual(projectNflResearch('nfl-v2-o2-robust-opportunity6-production10-v1',target,history),projectNflResearch('nfl-v2-o2-robust-opportunity6-production10-v1',target,history));});
