/* eslint-disable @typescript-eslint/no-require-imports */
const assert=require('node:assert/strict'),test=require('node:test'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(module,filename)=>module._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true},fileName:filename}).outputText,filename);
const {acquireNflObservations}=require('../lib/analytics/nfl/observationAcquisition.ts');
const {persistNflObservationBatch}=require('../lib/analytics/nfl/observationPersistence.server.ts');
const {hashNflObservation}=require('../lib/analytics/nfl/observationFoundation.ts');
const {nflObservationHashLookupGroups,NFL_OBSERVATION_HASH_LOOKUP_BATCH_SIZE}=require('../lib/analytics/nfl/observationIngestion.ts');
const {espnNflRegularSeasonScoreboardWeekUrl,normalizeEspnNflRegularSeasonScoreboard,mergeEspnNflRegularSeasonScoreboards}=require('../lib/analytics/providers/espnNflScoreboard.ts');
const eligible=[{localPlayerId:80,providerPlayerId:'42',position:'QB'},{localPlayerId:81,providerPlayerId:'43',position:'RB'}];
function log(position='QB',eventId='100',playerId=position==='QB'?'42':'43'){return {provider:'espn',providerPlayerId:playerId,playerName:null,position,season:2026,phase:'regular',week:1,eventId,gameAt:'2026-09-14T17:00:00.000Z',team:{providerId:'1',abbreviation:'AAA'},opponent:{providerId:'2',abbreviation:'BBB'},homeAway:'home',stats:{completions:position==='QB'?20:null,passingAttempts:position==='QB'?30:null,passingYards:position==='QB'?220:null,passingTouchdowns:position==='QB'?2:null,interceptions:position==='QB'?1:null,rushingAttempts:1,rushingYards:3,rushingTouchdowns:0,receivingTargets:position==='QB'?null:4,receptions:position==='QB'?null:3,receivingYards:position==='QB'?null:31,receivingTouchdowns:position==='QB'?null:0,fumblesLost:position==='QB'?null:0},provenance:{source:'https://espn.test/log',fetchedAt:'2026-09-15T03:00:00.000Z',knownAt:null}}}
const final=[{providerEventId:'100',season:2026,phase:'regular',completed:true}];
async function observations(logs,summary){return acquireNflObservations({eligible,season:2026,finalEvents:final,gameLogs:logs,fetchFumbles:async id=>summary(id)})}
test('only supported direct-ESPN identities in completed regular events become observations',async()=>{const rows=await observations([log(),log('RB')],async id=>({eventId:id,source:'https://espn.test/summary',fetchedAt:'2026-09-15T03:01:00.000Z',athletes:[]}));assert.equal(rows.length,2);assert.equal(rows[0].localPlayerId,80);assert.equal(rows[1].localPlayerId,81);assert.equal(rows[0].stats.fumblesLost,0);assert.equal(rows[1].provenance.fumbleSummarySourceUrl,null);assert.throws(()=>require('../lib/analytics/nfl/observationIngestion.ts').resolveDirectNflIdentity({providerPlayerId:'42',position:'K',eligible}));});
test('same-event QB summary evidence never leaks onto an RB observation',async()=>{const rows=await observations([log(),log('RB')],async id=>({eventId:id,source:'https://espn.test/summary',fetchedAt:'2026-09-15T03:01:00.000Z',athletes:[{providerPlayerId:'42',fumblesLost:1},{providerPlayerId:'43',fumblesLost:1}]}));const qb=rows.find(row=>row.position==='QB'),rb=rows.find(row=>row.position==='RB');assert.equal(qb.stats.fumblesLost,1);assert.match(qb.provenance.fumbleSummarySourceUrl,/summary/);assert.equal(rb.stats.fumblesLost,0);assert.equal(rb.provenance.fumbleSummarySourceUrl,null);assert.equal(rb.provenance.fumbleSummaryFetchedAt,null);});
test('non-final events are withheld and each QB event summary is fetched once',async()=>{let calls=0;const rows=await acquireNflObservations({eligible,season:2026,finalEvents:[],gameLogs:[log()],fetchFumbles:async()=>{calls++;return {}}});assert.deepEqual(rows,[]);assert.equal(calls,0);const twoQbs=[...eligible,{localPlayerId:82,providerPlayerId:'44',position:'QB'}];const second=log('QB','100','44');const result=await acquireNflObservations({eligible:twoQbs,season:2026,finalEvents:final,gameLogs:[log(),second],fetchFumbles:async id=>{calls++;return {eventId:id,source:'https://espn.test/summary',fetchedAt:'2026-09-15T03:01:00.000Z',athletes:[]}}});assert.equal(result.length,2);assert.equal(calls,1);});
test('positive QB LOST is retained and unvalidated summaries withhold all QB facts',async()=>{const positive=await observations([log()],async id=>({eventId:id,source:'https://espn.test/summary',fetchedAt:'2026-09-15T03:01:00.000Z',athletes:[{providerPlayerId:'42',fumblesLost:1}]}));assert.equal(positive[0].stats.fumblesLost,1);await assert.rejects(observations([log()],async()=>{throw new Error('missing LOST') }),/missing LOST/);});
test('scoreboard recognizes only explicit final regular-season events',()=>{const payload={events:[{id:'100',season:{year:2026,type:2},competitions:[{status:{type:{state:'post',completed:true}}}]},{id:'101',season:{year:2026,type:2},competitions:[{status:{type:{state:'in',completed:false}}}]},{id:'102',season:{year:2026,type:1},competitions:[{status:{type:{state:'post',completed:true}}}]}]};assert.deepEqual(normalizeEspnNflRegularSeasonScoreboard(payload,2026),[{providerEventId:'100',season:2026,phase:'regular',completed:true},{providerEventId:'101',season:2026,phase:'regular',completed:false}]);});
test('historical scoreboard acquisition enumerates bounded regular-season weeks and safely merges them',()=>{const week=(number,events)=>({events:events.map(event=>({id:event.id,week:{number},season:{year:2025,type:event.type??2},competitions:[{status:{type:{state:event.state??'post',completed:event.completed??true}}}]}))});const first=normalizeEspnNflRegularSeasonScoreboard(week(1,[{id:'100'},{id:'101',completed:false,state:'in'},{id:'102',type:1}]),2025,1),last=normalizeEspnNflRegularSeasonScoreboard(week(18,[{id:'200'}]),2025,18);assert.deepEqual(mergeEspnNflRegularSeasonScoreboards([first,last,[first[0]]]),[{providerEventId:'100',season:2025,phase:'regular',completed:true},{providerEventId:'101',season:2025,phase:'regular',completed:false},{providerEventId:'200',season:2025,phase:'regular',completed:true}]);assert.match(espnNflRegularSeasonScoreboardWeekUrl(2025,18),/dates=2025.*seasontype=2.*week=18/);assert.throws(()=>normalizeEspnNflRegularSeasonScoreboard(week(2,[{id:'103'}]),2025,1),/wrong week/);assert.throws(()=>mergeEspnNflRegularSeasonScoreboards([[first[0]],[{...first[0],completed:false}]]),/Conflicting/);});
test('server persistence validates the whole batch, dedupes exact facts, and permits corrections',async()=>{const [row]=await observations([log()],async id=>({eventId:id,source:'https://espn.test/summary',fetchedAt:'2026-09-15T03:01:00.000Z',athletes:[]}));const inserted=[];const hashes=new Set();const repo={loadEligiblePlayers:async()=>eligible,existingHashes:async values=>new Set(values.filter(x=>hashes.has(x))),insertVersions:async rows=>{rows.forEach(x=>{hashes.add(x.observation_hash);inserted.push(x)})}};assert.deepEqual(await persistNflObservationBatch({observations:[row],repository:repo}),{received:1,inserted:1,duplicate:0,rejected:0});assert.equal((await persistNflObservationBatch({observations:[row],repository:repo})).duplicate,1);const corrected={...row,stats:{...row.stats,passingYards:221}};assert.notEqual(hashNflObservation(row),hashNflObservation(corrected));assert.equal((await persistNflObservationBatch({observations:[corrected],repository:repo})).inserted,1);await assert.rejects(persistNflObservationBatch({observations:[{bad:true}],repository:repo}));assert.equal(inserted.length,2);});
test('hash lookup groups keep a 500-observation ingest below PostgREST filter limits',()=>{const hashes=Array.from({length:500},(_,i)=>i.toString(16).padStart(64,'0'));const groups=nflObservationHashLookupGroups(hashes);assert.equal(NFL_OBSERVATION_HASH_LOOKUP_BATCH_SIZE,50);assert.equal(groups.length,10);assert.ok(groups.every(group=>group.length<=50));assert.deepEqual(groups.flat(),hashes);assert.equal(nflObservationHashLookupGroups([...hashes,hashes[0]]).flat().length,500);});
test('a 500-row first batch inserts independent facts, ignores exact repeats, and appends a correction',async()=>{const [template]=await observations([log()],async id=>({eventId:id,source:'https://espn.test/summary',fetchedAt:'2026-09-15T03:01:00.000Z',athletes:[]}));const batch=Array.from({length:500},(_,i)=>({...template,providerPlayerId:String(1000+i),providerEventId:String(2000+i),localPlayerId:i+1}));const manyEligible=batch.map(row=>({localPlayerId:row.localPlayerId,providerPlayerId:row.providerPlayerId,position:'QB'}));const stored=new Set(),inserted=[];const repo={loadEligiblePlayers:async()=>manyEligible,existingHashes:async values=>new Set(values.filter(x=>stored.has(x))),insertVersions:async rows=>rows.forEach(row=>{stored.add(row.observation_hash);inserted.push(row)})};assert.equal(new Set(batch.map(hashNflObservation)).size,500);assert.equal((await persistNflObservationBatch({observations:batch,repository:repo})).inserted,500);assert.equal((await persistNflObservationBatch({observations:batch,repository:repo})).duplicate,500);const correction={...batch[0],stats:{...batch[0].stats,passingYards:221}};assert.equal((await persistNflObservationBatch({observations:[correction],repository:repo})).inserted,1);assert.equal(inserted.length,501);});
test('Phase B acquisition remains separate from Phase C generation/cache code',()=>{const files=['lib/analytics/nfl/observationAcquisition.ts','lib/analytics/nfl/observationPersistence.server.ts','scripts/run-nfl-projection-observation-refresh.cjs'];for(const file of files)assert.doesNotMatch(fs.readFileSync(file,'utf8'),/generateNfl|projection_stat_cache|nfl_projection_stat_cache/i);});
