/* eslint-disable @typescript-eslint/no-require-imports */
const assert=require('node:assert/strict'),test=require('node:test'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(module,filename)=>module._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true},fileName:filename}).outputText,filename);
const {acquireNflObservations}=require('../lib/analytics/nfl/observationAcquisition.ts');
const {persistNflObservationBatch}=require('../lib/analytics/nfl/observationPersistence.server.ts');
const {hashNflObservation}=require('../lib/analytics/nfl/observationFoundation.ts');
const {normalizeEspnNflRegularSeasonScoreboard}=require('../lib/analytics/providers/espnNflScoreboard.ts');
const eligible=[{localPlayerId:80,providerPlayerId:'42',position:'QB'},{localPlayerId:81,providerPlayerId:'43',position:'RB'}];
function log(position='QB',eventId='100',playerId=position==='QB'?'42':'43'){return {provider:'espn',providerPlayerId:playerId,playerName:null,position,season:2026,phase:'regular',week:1,eventId,gameAt:'2026-09-14T17:00:00.000Z',team:{providerId:'1',abbreviation:'AAA'},opponent:{providerId:'2',abbreviation:'BBB'},homeAway:'home',stats:{completions:position==='QB'?20:null,passingAttempts:position==='QB'?30:null,passingYards:position==='QB'?220:null,passingTouchdowns:position==='QB'?2:null,interceptions:position==='QB'?1:null,rushingAttempts:1,rushingYards:3,rushingTouchdowns:0,receivingTargets:position==='QB'?null:4,receptions:position==='QB'?null:3,receivingYards:position==='QB'?null:31,receivingTouchdowns:position==='QB'?null:0,fumblesLost:position==='QB'?null:0},provenance:{source:'https://espn.test/log',fetchedAt:'2026-09-15T03:00:00.000Z',knownAt:null}}}
const final=[{providerEventId:'100',season:2026,phase:'regular',completed:true}];
async function observations(logs,summary){return acquireNflObservations({eligible,season:2026,finalEvents:final,gameLogs:logs,fetchFumbles:async id=>summary(id)})}
test('only supported direct-ESPN identities in completed regular events become observations',async()=>{const rows=await observations([log(),log('RB')],async id=>({eventId:id,source:'https://espn.test/summary',fetchedAt:'2026-09-15T03:01:00.000Z',athletes:[]}));assert.equal(rows.length,2);assert.equal(rows[0].localPlayerId,80);assert.equal(rows[1].localPlayerId,81);assert.equal(rows[0].stats.fumblesLost,0);assert.equal(rows[1].provenance.fumbleSummarySourceUrl,null);assert.throws(()=>require('../lib/analytics/nfl/observationIngestion.ts').resolveDirectNflIdentity({providerPlayerId:'42',position:'K',eligible}));});
test('same-event QB summary evidence never leaks onto an RB observation',async()=>{const rows=await observations([log(),log('RB')],async id=>({eventId:id,source:'https://espn.test/summary',fetchedAt:'2026-09-15T03:01:00.000Z',athletes:[{providerPlayerId:'42',fumblesLost:1},{providerPlayerId:'43',fumblesLost:1}]}));const qb=rows.find(row=>row.position==='QB'),rb=rows.find(row=>row.position==='RB');assert.equal(qb.stats.fumblesLost,1);assert.match(qb.provenance.fumbleSummarySourceUrl,/summary/);assert.equal(rb.stats.fumblesLost,0);assert.equal(rb.provenance.fumbleSummarySourceUrl,null);assert.equal(rb.provenance.fumbleSummaryFetchedAt,null);});
test('non-final events are withheld and each QB event summary is fetched once',async()=>{let calls=0;const rows=await acquireNflObservations({eligible,season:2026,finalEvents:[],gameLogs:[log()],fetchFumbles:async()=>{calls++;return {}}});assert.deepEqual(rows,[]);assert.equal(calls,0);const twoQbs=[...eligible,{localPlayerId:82,providerPlayerId:'44',position:'QB'}];const second=log('QB','100','44');const result=await acquireNflObservations({eligible:twoQbs,season:2026,finalEvents:final,gameLogs:[log(),second],fetchFumbles:async id=>{calls++;return {eventId:id,source:'https://espn.test/summary',fetchedAt:'2026-09-15T03:01:00.000Z',athletes:[]}}});assert.equal(result.length,2);assert.equal(calls,1);});
test('positive QB LOST is retained and unvalidated summaries withhold all QB facts',async()=>{const positive=await observations([log()],async id=>({eventId:id,source:'https://espn.test/summary',fetchedAt:'2026-09-15T03:01:00.000Z',athletes:[{providerPlayerId:'42',fumblesLost:1}]}));assert.equal(positive[0].stats.fumblesLost,1);await assert.rejects(observations([log()],async()=>{throw new Error('missing LOST') }),/missing LOST/);});
test('scoreboard recognizes only explicit final regular-season events',()=>{const payload={events:[{id:'100',season:{year:2026,type:2},competitions:[{status:{type:{state:'post',completed:true}}}]},{id:'101',season:{year:2026,type:2},competitions:[{status:{type:{state:'in',completed:false}}}]},{id:'102',season:{year:2026,type:1},competitions:[{status:{type:{state:'post',completed:true}}}]}]};assert.deepEqual(normalizeEspnNflRegularSeasonScoreboard(payload,2026),[{providerEventId:'100',season:2026,phase:'regular',completed:true},{providerEventId:'101',season:2026,phase:'regular',completed:false}]);});
test('server persistence validates the whole batch, dedupes exact facts, and permits corrections',async()=>{const [row]=await observations([log()],async id=>({eventId:id,source:'https://espn.test/summary',fetchedAt:'2026-09-15T03:01:00.000Z',athletes:[]}));const inserted=[];const hashes=new Set();const repo={loadEligiblePlayers:async()=>eligible,existingHashes:async values=>new Set(values.filter(x=>hashes.has(x))),insertVersions:async rows=>{rows.forEach(x=>{hashes.add(x.observation_hash);inserted.push(x)})}};assert.deepEqual(await persistNflObservationBatch({observations:[row],repository:repo}),{received:1,inserted:1,duplicate:0,rejected:0});assert.equal((await persistNflObservationBatch({observations:[row],repository:repo})).duplicate,1);const corrected={...row,stats:{...row.stats,passingYards:221}};assert.notEqual(hashNflObservation(row),hashNflObservation(corrected));assert.equal((await persistNflObservationBatch({observations:[corrected],repository:repo})).inserted,1);await assert.rejects(persistNflObservationBatch({observations:[{bad:true}],repository:repo}));assert.equal(inserted.length,2);});
test('Phase B code contains no projection generation or cache contract',()=>{const files=['lib/analytics/nfl/observationAcquisition.ts','lib/analytics/nfl/observationPersistence.server.ts','app/api/internal/nfl/projection-ingest/route.ts','scripts/run-nfl-projection-observation-refresh.cjs'];for(const file of files)assert.doesNotMatch(fs.readFileSync(file,'utf8'),/generateNfl|projection_stat_cache|nfl_projection_stat_cache/i);});
