"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import AppNav from "@/components/AppNav";

type AdminData = { detail: { contest: { status: string; lockAt: string | null; maxBracketsPerEntrant: number; managedEntrantsAllowed: boolean }; competition: { name: string } }; settings: { status: string; lockAt: string | null; maxBracketsPerEntrant: number; managedEntrantsAllowed: boolean; roundPoints: Record<string, number> }; rounds: { key: string; label: string }[]; summary: { entrants: number; entries: number; frozen: number; complete: number; incomplete: number; managedEntrants: number } };
const lockStates = new Set(["locked", "in_progress", "final"]);
export default function BracketContestAdminPage() {
  const { contestId } = useParams<{ contestId: string }>(); const [data, setData] = useState<AdminData | null>(null); const [form, setForm] = useState<AdminData["settings"] | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const load = () => void fetch(`/api/bracket-challenge/contests/${encodeURIComponent(contestId)}/admin`, { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to load contest settings."); return body as AdminData; }).then((body) => { setData(body); setForm(body.settings); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Unable to load contest settings."));
  useEffect(load, [contestId]);
  async function save() { if (!form) return; setSaving(true); setError(""); setMessage(""); try { const currentLocked = data && (lockStates.has(data.settings.status) || Boolean(data.settings.lockAt && new Date(data.settings.lockAt).getTime() <= Date.now())); const nextLocked = lockStates.has(form.status) || Boolean(form.lockAt && new Date(form.lockAt).getTime() <= Date.now()); const entersLock = Boolean(!currentLocked && nextLocked); if (entersLock && !window.confirm("Locking freezes every admitted bracket with its current picks and rules. This cannot be undone for those entries. Continue?")) return; const response = await fetch(`/api/bracket-challenge/contests/${encodeURIComponent(contestId)}/admin`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, lockAt: form.lockAt || null, confirmLock: entersLock }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to save contest settings."); setData(body); setForm(body.settings); setMessage("Contest settings saved. Frozen entries retain their original rules."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save contest settings."); } finally { setSaving(false); } }
  if (!data || !form) return <main className="min-h-screen bg-slate-950 p-5 text-slate-300">{error || "Loading commissioner controls…"}</main>;
  return <main className="min-h-screen bg-slate-950 px-3 py-5 pb-24 text-slate-100 sm:px-4 sm:py-6"><div className="mx-auto max-w-3xl"><AppNav /><Link href={`/bracket-challenge/${contestId}`} className="mt-5 inline-block text-sm font-bold text-blue-300">← Challenge home</Link><h1 className="mt-4 text-3xl font-black text-white">Bracket Challenge controls</h1><p className="mt-1 text-sm text-slate-400">{data.detail.competition.name} · current contest configuration</p>
    <section className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-3">{Object.entries(data.summary).map(([key, value]) => <div key={key} className="rounded-xl border border-slate-800 bg-slate-900/70 p-3"><p className="text-xl font-black text-white">{value}</p><p className="text-xs capitalize text-slate-400">{key.replace(/([A-Z])/g, " $1")}</p></div>)}</section>
    <section className="mt-5 space-y-5 rounded-2xl border border-slate-800 bg-slate-900/70 p-4 sm:p-5"><div><h2 className="font-black text-white">Contest settings</h2><p className="mt-1 text-sm text-slate-400">These are current settings for future admissions and freezes. They never rewrite frozen entries.</p></div><label className="block text-sm font-bold">Status<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })} className="mt-1 block w-full rounded-xl border border-slate-700 bg-slate-950 p-3 text-white"><option value="setup">Setup</option><option value="locked">Locked</option><option value="in_progress">In progress</option><option value="final">Final</option></select></label><label className="block text-sm font-bold">Contest lock time (optional)<input type="datetime-local" value={form.lockAt ? form.lockAt.slice(0, 16) : ""} onChange={(event) => setForm({ ...form, lockAt: event.target.value ? new Date(event.target.value).toISOString() : null })} className="mt-1 block w-full rounded-xl border border-slate-700 bg-slate-950 p-3 text-white" /></label><label className="block text-sm font-bold">Max brackets per entrant<input type="number" min="1" step="1" value={form.maxBracketsPerEntrant} onChange={(event) => setForm({ ...form, maxBracketsPerEntrant: Number(event.target.value) })} className="mt-1 block w-full rounded-xl border border-slate-700 bg-slate-950 p-3 text-white" /></label><label className="flex gap-3 text-sm"><input type="checkbox" checked={form.managedEntrantsAllowed} onChange={(event) => setForm({ ...form, managedEntrantsAllowed: event.target.checked })} />Allow managed entrants</label></section>
    <section className="mt-5 rounded-2xl border border-slate-800 bg-slate-900/70 p-4 sm:p-5"><h2 className="font-black text-white">Round scoring</h2><p className="mt-1 text-sm text-slate-400">Whole, non-negative points. Changes apply only to later frozen entries.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.rounds.map((round) => <label key={round.key} className="text-sm font-bold">{round.label}<input type="number" min="0" step="1" value={form.roundPoints[round.key] ?? 0} onChange={(event) => setForm({ ...form, roundPoints: { ...form.roundPoints, [round.key]: Number(event.target.value) } })} className="mt-1 block w-full rounded-xl border border-slate-700 bg-slate-950 p-3 text-white" /></label>)}</div><p className="mt-4 text-xs text-slate-500">Tiebreaker: Championship Total Points is retained in each frozen entry. It is only used when a valid final official total is available.</p></section>
    {lockStates.has(form.status) && !lockStates.has(data.settings.status) && <p className="mt-4 rounded-xl border border-amber-400/40 bg-amber-950/30 p-3 text-sm text-amber-100">Saving this status will freeze all admitted brackets. Existing frozen brackets cannot be unlocked.</p>}{error && <p className="mt-4 text-sm text-red-300">{error}</p>}{message && <p className="mt-4 text-sm text-emerald-300">{message}</p>}<button type="button" disabled={saving} onClick={() => void save()} className="mt-5 rounded-xl bg-blue-500 px-5 py-3 text-sm font-black text-white disabled:opacity-50">{saving ? "Saving…" : "Save contest settings"}</button>
  </div></main>;
}
