"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import AppNav from "@/components/AppNav";
import { competitionCategoryIdentity, competitionIdentity, defaultBracketHomeSeason, filterBracketHomeCompetitions } from "@/lib/bracket/homeBrowser";

type CompetitionItem = { competition: { id: number; sportKey: string; formatKey: string; season: number; name: string; status: string; startsAt: string | null; endsAt: string | null; gameCount: number }; contest: { contestId: string; contestStatus: string; contestLockAt: string | null; maxBracketsPerEntrant: number } | null; personalSummary: { totalBrackets: number; completeBrackets: number } | null };
type CompetitionsResponse = { group?: { id: string; name: string; slug: string }; competitions?: CompetitionItem[]; error?: string };
const titleCase = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const competitionLabels: Record<string, string> = { "college_football:cfp": "College Football · 12-team playoff", "mens_college_basketball:ncaa_mens": "Men's College Basketball · NCAA tournament", "womens_college_basketball:ncaa_womens": "Women's College Basketball · NCAA tournament", "nfl:nfl_playoffs": "NFL · Playoffs" };
const competitionCategoryLabels: Record<string, string> = { college_football: "College Football", mens_college_basketball: "Men's Basketball", womens_college_basketball: "Women's Basketball", nfl: "NFL" };
function competitionLabel(item: CompetitionItem) { return competitionLabels[competitionIdentity(item)] ?? `${titleCase(item.competition.sportKey)} · ${titleCase(item.competition.formatKey)}`; }
function competitionCategoryLabel(item: CompetitionItem) { return competitionCategoryLabels[competitionCategoryIdentity(item)] ?? titleCase(item.competition.sportKey); }
function stateLabel(item: CompetitionItem, now = new Date()) {
  if (item.contest) return ({ open: "Editable", locked: "Locked", in_progress: "Live", final: "Final" }[item.contest.contestStatus] ?? "Setup");
  if (item.competition.status === "final" || (item.competition.endsAt && new Date(item.competition.endsAt).getTime() < now.getTime())) return "Historical";
  if (item.competition.status === "in_progress") return "Live";
  if (item.competition.startsAt && new Date(item.competition.startsAt).getTime() > now.getTime()) return "Upcoming";
  return item.competition.status === "open" ? "Open globally" : "Upcoming";
}
function progressLabel(summary: CompetitionItem["personalSummary"]) {
  if (!summary || summary.totalBrackets === 0) return null;
  if (summary.totalBrackets === 1) return summary.completeBrackets === 1 ? "Your bracket: Complete" : "Your bracket: In progress";
  return `Your brackets: ${summary.completeBrackets} of ${summary.totalBrackets} complete`;
}

export default function BracketChallengePage() {
  const [data, setData] = useState<CompetitionsResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [season, setSeason] = useState<number | null>(null);
  const [competitionKey, setCompetitionKey] = useState("all");
  useEffect(() => { let cancelled = false; void fetch("/api/bracket-challenge/competitions", { cache: "no-store" }).then(async (response) => { const result = await response.json() as CompetitionsResponse; if (!response.ok) throw new Error(result.error ?? "Unable to load Bracket Challenge."); return result; }).then((result) => { if (!cancelled) { setData(result); setSeason((current) => current ?? defaultBracketHomeSeason(result.competitions ?? [])); } }).catch((reason: unknown) => { if (!cancelled) setError(reason instanceof Error ? reason.message : "Unable to load Bracket Challenge."); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, []);
  const competitions = data?.competitions ?? [];
  const years = useMemo(() => [...new Set(competitions.map((item) => item.competition.season))].sort((a, b) => b - a), [competitions]);
  const competitionOptions = useMemo(() => { const choices = new Map<string, string>(); for (const item of competitions) choices.set(competitionCategoryIdentity(item), competitionCategoryLabel(item)); return [...choices.entries()].sort(([, a], [, b]) => a.localeCompare(b)); }, [competitions]);
  const filtered = filterBracketHomeCompetitions(competitions, season, competitionKey);
  return <main className="min-h-screen bg-slate-950 px-3 py-5 pb-24 text-slate-100 sm:px-4 sm:py-6 sm:pb-6"><div className="mx-auto max-w-5xl space-y-6"><AppNav />
    <section className="rounded-3xl border border-blue-500/30 bg-gradient-to-br from-slate-900 via-slate-900 to-blue-950 p-5 shadow-xl sm:p-7"><div className="text-xs font-black uppercase tracking-[0.2em] text-blue-300">111 Sports</div><h1 className="mt-2 text-3xl font-black tracking-tight text-white sm:text-4xl">Bracket Challenge</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Browse every tournament challenge available to your Group—current, upcoming, and historical.</p>{data?.group?.name ? <div className="mt-4 text-xs font-bold uppercase tracking-[0.16em] text-slate-400">{data.group.name}</div> : null}</section>
    <section><div className="mb-3"><div className="text-xs font-black uppercase tracking-[0.18em] text-blue-300">Competition browser</div><h2 className="mt-1 text-xl font-black text-white">Your Group&apos;s challenges</h2></div>
      {!loading && !error && competitions.length > 0 ? <div className="mb-4 flex flex-wrap gap-2" aria-label="Bracket Challenge filters"><label className="flex min-w-0 flex-1 items-center gap-2 rounded-xl border border-slate-700 bg-slate-900 px-3 py-2 text-xs font-bold text-slate-300 sm:flex-none"><span className="text-[10px] uppercase tracking-wide text-slate-500">Year</span><select value={season ?? ""} onChange={(event) => setSeason(event.target.value ? Number(event.target.value) : null)} className="min-w-0 bg-transparent text-sm font-bold text-white outline-none">{years.map((year) => <option key={year} value={year} className="bg-slate-900">{year}</option>)}</select></label><label className="flex min-w-0 flex-[2] items-center gap-2 rounded-xl border border-slate-700 bg-slate-900 px-3 py-2 text-xs font-bold text-slate-300 sm:flex-none"><span className="shrink-0 text-[10px] uppercase tracking-wide text-slate-500">Competition</span><select value={competitionKey} onChange={(event) => setCompetitionKey(event.target.value)} className="min-w-0 flex-1 bg-transparent text-sm font-bold text-white outline-none"><option value="all" className="bg-slate-900">All</option>{competitionOptions.map(([key, label]) => <option key={key} value={key} className="bg-slate-900">{label}</option>)}</select></label></div> : null}
      {loading ? <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5 text-sm text-slate-400">Loading challenges…</div> : error ? <div className="rounded-2xl border border-red-500/30 bg-red-950/20 p-5 text-sm text-red-200">{error}</div> : competitions.length === 0 ? <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><div className="font-bold text-white">No competitions available</div><p className="mt-1 text-sm leading-6 text-slate-400">There are no Bracket Challenge competitions to browse yet.</p></div> : filtered.length === 0 ? <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5 text-sm text-slate-400">No competitions match these filters.</div> : <div className="grid gap-3">{filtered.map((item) => { const progress = progressLabel(item.personalSummary); return <article key={item.competition.id} className="rounded-2xl border border-slate-700/70 bg-[linear-gradient(145deg,rgba(15,23,42,0.96),rgba(15,23,42,0.72))] p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="text-[10px] font-black uppercase tracking-[0.18em] text-blue-300">{item.competition.season}</div><h3 className="mt-1 text-lg font-black text-white">{item.competition.name}</h3><p className="mt-1 text-sm text-slate-400">{competitionLabel(item)}{item.competition.gameCount > 0 ? ` · ${item.competition.gameCount} ${item.competition.gameCount === 1 ? "game" : "games"}` : ""}</p></div><span className="shrink-0 rounded-full bg-blue-300/10 px-2.5 py-1 text-[10px] font-black uppercase tracking-wide text-blue-200">{stateLabel(item)}</span></div><div className="mt-4 flex items-center justify-between gap-3 border-t border-slate-700/70 pt-3">{item.contest ? <span className="text-xs text-slate-400">{progress ?? `Up to ${item.contest.maxBracketsPerEntrant} ${item.contest.maxBracketsPerEntrant === 1 ? "bracket" : "brackets"} per entrant`}</span> : <span className="text-xs text-slate-400">Not set up for this Group</span>}{item.contest ? <Link href={`/bracket-challenge/${encodeURIComponent(item.contest.contestId)}`} className="text-xs font-bold text-blue-300 transition hover:text-blue-200">View Challenge <span aria-hidden="true">→</span></Link> : <span className="text-xs font-bold text-slate-500">Group contest unavailable</span>}</div></article>; })}</div>}
    </section></div></main>;
}
