begin;

create table if not exists public.ncaa_pickem_weeks (
  id bigint generated by default as identity primary key,
  season integer not null,
  week_number integer not null,
  label text not null,
  lock_at timestamptz,
  status text not null default 'open'
    check (status in ('open', 'locked', 'final')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint ncaa_pickem_weeks_season_week_key
    unique (season, week_number)
);

create table if not exists public.ncaa_pickem_games (
  id bigint generated by default as identity primary key,
  week_id bigint not null
    references public.ncaa_pickem_weeks(id)
    on delete cascade,

  espn_event_id text not null unique,
  kickoff_at timestamptz not null,

  away_team_id text not null,
  away_team_name text not null,
  away_team_abbreviation text,
  away_team_logo_url text,
  away_rank integer,
  away_record text,
  away_score integer,

  home_team_id text not null,
  home_team_name text not null,
  home_team_abbreviation text,
  home_team_logo_url text,
  home_rank integer,
  home_record text,
  home_score integer,

  status text not null default 'scheduled',
  status_detail text,
  winner_team_id text,

  away_stats jsonb not null default '{}'::jsonb,
  home_stats jsonb not null default '{}'::jsonb,

  included boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists
  ncaa_pickem_games_week_id_idx
on public.ncaa_pickem_games (week_id);

create index if not exists
  ncaa_pickem_games_kickoff_at_idx
on public.ncaa_pickem_games (kickoff_at);

create table if not exists public.ncaa_pickem_picks (
  id bigint generated by default as identity primary key,

  week_id bigint not null
    references public.ncaa_pickem_weeks(id)
    on delete cascade,

  game_id bigint not null
    references public.ncaa_pickem_games(id)
    on delete cascade,

  team_id bigint not null
    references public.teams(id)
    on delete cascade,

  picked_team_id text not null,

  is_correct boolean,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint ncaa_pickem_picks_game_team_key
    unique (game_id, team_id)
);

create index if not exists
  ncaa_pickem_picks_week_team_idx
on public.ncaa_pickem_picks (week_id, team_id);

commit;
