-- NBA Skins independent-game foundation.
-- This intentionally does NOT reuse fantasy slates/lineups.

create table if not exists public.nba_skins_seasons (
  id bigint generated by default as identity primary key,
  season integer not null unique,
  status text not null default 'open'
    check (status in ('open', 'locked', 'final')),
  draft_locked_at timestamptz,
  finalized_at timestamptz,
  champion_team_id bigint
    references public.teams(id)
    on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.nba_skins_nba_teams (
  abbreviation text primary key,
  display_name text not null,
  nba_team_id text,
  espn_team_id text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.nba_skins_draft_order (
  id bigint generated by default as identity primary key,
  season_id bigint not null
    references public.nba_skins_seasons(id)
    on delete cascade,
  team_id bigint not null
    references public.teams(id)
    on delete cascade,
  draft_position integer not null
    check (draft_position between 1 and 4),
  created_at timestamptz not null default now(),

  constraint nba_skins_draft_order_team_unique
    unique (season_id, team_id),

  constraint nba_skins_draft_order_position_unique
    unique (season_id, draft_position)
);

create table if not exists public.nba_skins_picks (
  id bigint generated by default as identity primary key,
  season_id bigint not null
    references public.nba_skins_seasons(id)
    on delete cascade,
  team_id bigint not null
    references public.teams(id)
    on delete cascade,
  nba_team_abbreviation text not null
    references public.nba_skins_nba_teams(abbreviation)
    on delete restrict,
  pick_type text not null
    check (pick_type in ('wins', 'losses')),
  draft_round integer
    check (draft_round between 1 and 7),
  overall_pick integer,
  final_points integer
    check (final_points is null or final_points between 0 and 82),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint nba_skins_pick_nba_team_unique
    unique (season_id, nba_team_abbreviation),

  constraint nba_skins_pick_round_unique
    unique (season_id, team_id, draft_round),

  constraint nba_skins_pick_overall_unique
    unique (season_id, overall_pick)
);

create index if not exists nba_skins_picks_season_team_idx
  on public.nba_skins_picks (season_id, team_id);

create table if not exists public.nba_skins_team_records (
  id bigint generated by default as identity primary key,
  season_id bigint not null
    references public.nba_skins_seasons(id)
    on delete cascade,
  nba_team_abbreviation text not null
    references public.nba_skins_nba_teams(abbreviation)
    on delete cascade,
  wins integer not null default 0
    check (wins between 0 and 82),
  losses integer not null default 0
    check (losses between 0 and 82),
  games_played integer not null default 0
    check (games_played between 0 and 82),
  projected_wins numeric(5,2),
  projected_losses numeric(5,2),
  projection_source text,
  source_updated_at timestamptz,
  updated_at timestamptz not null default now(),

  constraint nba_skins_team_records_unique
    unique (season_id, nba_team_abbreviation)
);

alter table public.nba_skins_seasons
  enable row level security;

alter table public.nba_skins_nba_teams
  enable row level security;

alter table public.nba_skins_draft_order
  enable row level security;

alter table public.nba_skins_picks
  enable row level security;

alter table public.nba_skins_team_records
  enable row level security;

insert into public.nba_skins_nba_teams (
  abbreviation,
  display_name
)
values
  ('ATL', 'Atlanta Hawks'),
  ('BOS', 'Boston Celtics'),
  ('BKN', 'Brooklyn Nets'),
  ('CHA', 'Charlotte Hornets'),
  ('CHI', 'Chicago Bulls'),
  ('CLE', 'Cleveland Cavaliers'),
  ('DAL', 'Dallas Mavericks'),
  ('DEN', 'Denver Nuggets'),
  ('DET', 'Detroit Pistons'),
  ('GSW', 'Golden State Warriors'),
  ('HOU', 'Houston Rockets'),
  ('IND', 'Indiana Pacers'),
  ('LAC', 'Los Angeles Clippers'),
  ('LAL', 'Los Angeles Lakers'),
  ('MEM', 'Memphis Grizzlies'),
  ('MIA', 'Miami Heat'),
  ('MIL', 'Milwaukee Bucks'),
  ('MIN', 'Minnesota Timberwolves'),
  ('NOP', 'New Orleans Pelicans'),
  ('NYK', 'New York Knicks'),
  ('OKC', 'Oklahoma City Thunder'),
  ('ORL', 'Orlando Magic'),
  ('PHI', 'Philadelphia 76ers'),
  ('PHX', 'Phoenix Suns'),
  ('POR', 'Portland Trail Blazers'),
  ('SAC', 'Sacramento Kings'),
  ('SAS', 'San Antonio Spurs'),
  ('TOR', 'Toronto Raptors'),
  ('UTA', 'Utah Jazz'),
  ('WAS', 'Washington Wizards')
on conflict (abbreviation)
do update set
  display_name = excluded.display_name,
  updated_at = now();
