-- ============================================================
-- Bracket Challenge: competition field assignments
--
-- A bracket competition is global across Groups. Its field is
-- therefore also global.
--
-- Example:
--   competition 1 / seed 1 -> ESPN team 194 (Ohio State)
--
-- The tournament graph remains in bracket_games. This table
-- stores the authoritative team assigned to each seeded slot.
-- ============================================================

create table if not exists public.bracket_competition_teams (
  id bigint generated by default as identity primary key,

  competition_id bigint not null
    references public.bracket_competitions(id)
    on delete cascade,

  seed integer not null
    check (seed >= 1),

  provider text not null default 'espn'
    check (
      char_length(trim(provider))
      between 1 and 40
    ),

  provider_team_id text not null
    check (
      char_length(trim(provider_team_id))
      between 1 and 100
    ),

  display_name text not null
    check (
      char_length(trim(display_name))
      between 1 and 160
    ),

  abbreviation text,

  logo_url text,

  metadata jsonb not null default '{}'::jsonb
    check (
      jsonb_typeof(metadata) = 'object'
    ),

  created_at timestamptz not null default now(),

  updated_at timestamptz not null default now(),

  constraint bracket_competition_teams_competition_seed_key
    unique (
      competition_id,
      seed
    ),

  constraint bracket_competition_teams_provider_team_key
    unique (
      competition_id,
      provider,
      provider_team_id
    )
);

create index if not exists
  bracket_competition_teams_competition_idx
on public.bracket_competition_teams (
  competition_id,
  seed
);

alter table public.bracket_competition_teams
  enable row level security;

comment on table public.bracket_competition_teams is
  'Global seeded field assignments for a Bracket Challenge competition. Runtime access is server-mediated.';

comment on column public.bracket_competition_teams.seed is
  'Tournament seed/slot. Seed identity is stable even when the assigned team changes during competition setup.';

comment on column public.bracket_competition_teams.provider_team_id is
  'Canonical provider team identity, currently ESPN for CFP.';
