-- ============================================================
-- 111 SPORTS — BRACKET CHALLENGE FOUNDATION
--
-- Bracket Challenge is the permanent 111 Sports game.
--
-- Individual tournaments are competitions inside that game:
--   College Football Playoff
--   Men's March Madness
--   Women's March Madness
--   future NFL Playoffs
--   future bracket competitions
--
-- Competition/game truth is shared globally.
-- Group participation, rules, entries, and standings are
-- League-scoped.
-- ============================================================

begin;


-- ============================================================
-- 1. BRACKET CHALLENGE AS A LEAGUE SPORT
-- ============================================================

alter table public.leagues
  drop constraint if exists leagues_sport_key_check;

alter table public.leagues
  add constraint leagues_sport_key_check
  check (
    sport_key in (
      'nba',
      'nfl',
      'golf',
      'ncaa_pickem',
      'nba_skins',
      'bracket_challenge'
    )
  );


-- ============================================================
-- 2. COMPETITIONS
--
-- One row represents one real-world tournament.
--
-- Examples:
--
-- sport_key               format_key       season
-- ------------------------------------------------
-- college_football        cfp              2026
-- mens_college_basketball ncaa_mens        2027
-- womens_college_basketball ncaa_womens    2027
-- nfl                     nfl_playoffs      2027
--
-- These are intentionally NOT hardcoded into database CHECK
-- constraints. Adding a future bracket format should not require
-- rewriting the database schema.
-- ============================================================

create table if not exists public.bracket_competitions (
  id bigint generated by default as identity primary key,

  sport_key text not null
    check (
      char_length(trim(sport_key))
      between 1 and 80
    ),

  format_key text not null
    check (
      char_length(trim(format_key))
      between 1 and 80
    ),

  season integer not null
    check (
      season between 2000 and 2200
    ),

  name text not null
    check (
      char_length(trim(name))
      between 1 and 160
    ),

  status text not null default 'setup'
    check (
      status in (
        'setup',
        'open',
        'in_progress',
        'final'
      )
    ),

  provider text,

  provider_competition_id text,

  starts_at timestamptz,

  ends_at timestamptz,

  topology_version integer not null default 1
    check (
      topology_version >= 1
    ),

  metadata jsonb not null default '{}'::jsonb
    check (
      jsonb_typeof(metadata) = 'object'
    ),

  created_at timestamptz not null default now(),

  updated_at timestamptz not null default now(),

  constraint bracket_competitions_format_season_key
    unique (
      format_key,
      season
    ),

  constraint bracket_competitions_date_order_check
    check (
      ends_at is null
      or starts_at is null
      or ends_at >= starts_at
    )
);

create index if not exists
  bracket_competitions_status_idx
on public.bracket_competitions (
  status,
  season
);


-- ============================================================
-- 3. BRACKET GAMES
--
-- Each row is one game/node in the tournament graph.
--
-- Each source slot can be:
--
--   fixed team
--       source_*_team_id
--
--   OR
--
--   winner of an earlier game
--       source_*_game_id
--
-- This supports:
--
--   CFP
--   First Four -> Round of 64
--   NFL Wild Card -> later rounds
--   and other directed knockout brackets.
--
-- source_*_game_id is self-referential so the persisted graph
-- mirrors the pure lib/bracket engine.
-- ============================================================

create table if not exists public.bracket_games (
  id bigint generated by default as identity primary key,

  competition_id bigint not null
    references public.bracket_competitions(id)
    on delete cascade,

  game_key text not null
    check (
      char_length(trim(game_key))
      between 1 and 100
    ),

  round_key text not null
    check (
      char_length(trim(round_key))
      between 1 and 100
    ),

  round_order integer not null
    check (
      round_order >= 1
    ),

  game_order integer not null
    check (
      game_order >= 1
    ),

  region_key text,

  source_a_game_id bigint,

  source_b_game_id bigint,

  source_a_team_id text,

  source_b_team_id text,

  source_a_seed integer
    check (
      source_a_seed is null
      or source_a_seed >= 1
    ),

  source_b_seed integer
    check (
      source_b_seed is null
      or source_b_seed >= 1
    ),

  provider_event_id text,

  scheduled_at timestamptz,

  lock_at timestamptz,

  status text not null default 'scheduled'
    check (
      status in (
        'scheduled',
        'in_progress',
        'final'
      )
    ),

  winner_team_id text,

  metadata jsonb not null default '{}'::jsonb
    check (
      jsonb_typeof(metadata) = 'object'
    ),

  created_at timestamptz not null default now(),

  updated_at timestamptz not null default now(),

  constraint bracket_games_competition_game_key
    unique (
      competition_id,
      game_key
    ),

  constraint bracket_games_competition_order_key
    unique (
      competition_id,
      round_order,
      game_order
    ),

  constraint bracket_games_id_competition_key
    unique (
      id,
      competition_id
    ),

  constraint bracket_games_source_a_game_fk
    foreign key (
      source_a_game_id,
      competition_id
    )
    references public.bracket_games (
      id,
      competition_id
    )
    on delete restrict,

  constraint bracket_games_source_b_game_fk
    foreign key (
      source_b_game_id,
      competition_id
    )
    references public.bracket_games (
      id,
      competition_id
    )
    on delete restrict,

  constraint bracket_games_source_a_check
    check (
      not (
        source_a_game_id is not null
        and source_a_team_id is not null
      )
    ),

  constraint bracket_games_source_b_check
    check (
      not (
        source_b_game_id is not null
        and source_b_team_id is not null
      )
    )
);

create index if not exists
  bracket_games_competition_round_idx
on public.bracket_games (
  competition_id,
  round_order,
  game_order
);

create index if not exists
  bracket_games_provider_event_idx
on public.bracket_games (
  provider_event_id
)
where provider_event_id is not null;


-- ============================================================
-- 4. ENTRANTS
--
-- Bracket identity is deliberately independent of:
--
--   teams
--   Group membership
--   fantasy roster identity
--
-- An entrant can be:
--
-- ACCOUNT
--   A normal 111 Sports user.
--
-- MANAGED
--   Someone whose brackets are managed by an account, such as
--   Nico or Izzy.
--
-- A managed entrant may later be claimed by an account without
-- changing entrant_id, preserving all historical bracket results.
-- ============================================================

create table if not exists public.bracket_entrants (
  id uuid primary key default gen_random_uuid(),

  entrant_kind text not null
    check (
      entrant_kind in (
        'account',
        'managed'
      )
    ),

  display_name text not null
    check (
      char_length(trim(display_name))
      between 1 and 80
    ),

  account_user_id uuid
    references public.app_users(id)
    on delete set null,

  managing_user_id uuid
    references public.app_users(id)
    on delete restrict,

  claimed_at timestamptz,

  is_active boolean not null default true,

  created_at timestamptz not null default now(),

  updated_at timestamptz not null default now(),

  constraint bracket_entrants_identity_check
    check (
      (
        entrant_kind = 'account'
        and account_user_id is not null
        and managing_user_id is null
        and claimed_at is null
      )
      or
      (
        entrant_kind = 'managed'
        and managing_user_id is not null
        and (
          (
            account_user_id is null
            and claimed_at is null
          )
          or
          (
            account_user_id is not null
            and claimed_at is not null
          )
        )
      )
    )
);

create unique index if not exists
  bracket_entrants_account_user_unique
on public.bracket_entrants (
  account_user_id
)
where account_user_id is not null;

create index if not exists
  bracket_entrants_manager_idx
on public.bracket_entrants (
  managing_user_id
)
where managing_user_id is not null;


-- ============================================================
-- 5. ENTRIES
--
-- One entrant participating in one Group's Bracket Challenge
-- League for one competition.
--
-- The competition itself is global.
-- The ENTRY is League-owned.
--
-- Example:
--
--                 2027 Men's NCAA Tournament
--                           |
--             +-------------+-------------+
--             |                           |
--       Family Group                  111 Group
--       Bracket League                Bracket League
--             |                           |
--       Mark entry                    Mark entry
--       Nico entry                    Josh entry
--       Izzy entry                    Andy entry
--
-- rules_snapshot freezes the rules/configuration governing this
-- Group entry.
--
-- picks_snapshot is the immutable lock-time bracket. Editable
-- normalized selections live in bracket_picks.
-- ============================================================

create table if not exists public.bracket_entries (
  id bigint generated by default as identity primary key,

  competition_id bigint not null
    references public.bracket_competitions(id)
    on delete restrict,

  league_id uuid not null
    references public.leagues(id)
    on delete restrict,

  entrant_id uuid not null
    references public.bracket_entrants(id)
    on delete restrict,

  status text not null default 'draft'
    check (
      status in (
        'draft',
        'submitted',
        'locked',
        'final'
      )
    ),

  rules_version integer not null default 1
    check (
      rules_version >= 1
    ),

  rules_snapshot jsonb not null default '{}'::jsonb
    check (
      jsonb_typeof(rules_snapshot) = 'object'
    ),

  picks_snapshot jsonb
    check (
      picks_snapshot is null
      or jsonb_typeof(picks_snapshot) = 'object'
    ),

  tiebreaker_value integer
    check (
      tiebreaker_value is null
      or tiebreaker_value >= 0
    ),

  submitted_at timestamptz,

  locked_at timestamptz,

  created_at timestamptz not null default now(),

  updated_at timestamptz not null default now(),

  constraint bracket_entries_league_competition_entrant_key
    unique (
      league_id,
      competition_id,
      entrant_id
    ),

  constraint bracket_entries_id_competition_key
    unique (
      id,
      competition_id
    )
);

create index if not exists
  bracket_entries_competition_league_idx
on public.bracket_entries (
  competition_id,
  league_id
);

create index if not exists
  bracket_entries_entrant_idx
on public.bracket_entries (
  entrant_id,
  competition_id
);


-- ============================================================
-- 6. PICKS
--
-- Normalized editable bracket selections.
--
-- picked_team_id is the predicted winner of that game node.
--
-- Dependency validity remains application-domain logic. That
-- allows the pure bracket engine to:
--
--   clear invalid future picks when the USER changes an
--   upstream selection before lock
--
-- while preserving historical picks when an ACTUAL RESULT
-- eliminates that team after lock.
-- ============================================================

create table if not exists public.bracket_picks (
  id bigint generated by default as identity primary key,

  entry_id bigint not null,

  competition_id bigint not null,

  game_id bigint not null,

  picked_team_id text not null,

  is_correct boolean,

  points_awarded numeric not null default 0,

  created_at timestamptz not null default now(),

  updated_at timestamptz not null default now(),

  constraint bracket_picks_entry_game_key
    unique (
      entry_id,
      game_id
    ),

  constraint bracket_picks_entry_competition_fk
    foreign key (
      entry_id,
      competition_id
    )
    references public.bracket_entries (
      id,
      competition_id
    )
    on delete cascade,

  constraint bracket_picks_game_competition_fk
    foreign key (
      game_id,
      competition_id
    )
    references public.bracket_games (
      id,
      competition_id
    )
    on delete restrict
);

create index if not exists
  bracket_picks_entry_idx
on public.bracket_picks (
  entry_id
);

create index if not exists
  bracket_picks_game_idx
on public.bracket_picks (
  game_id
);


-- ============================================================
-- 7. LEAGUE COMPATIBILITY
--
-- An entry must belong to a League whose permanent 111 Sports
-- game is Bracket Challenge.
--
-- league_id remains the authoritative Group-scoped container.
-- This trigger prevents accidental attachment of a bracket entry
-- to an NBA, NFL, Golf, NCAA Pick'em, or NBA Skins League.
-- ============================================================

create or replace function public.validate_bracket_entry_league()
returns trigger
language plpgsql
as $$
declare
  league_sport_key text;
begin
  select l.sport_key
    into league_sport_key
  from public.leagues l
  where l.id = new.league_id;

  if league_sport_key is null then
    raise exception
      'Bracket entry references unknown league %',
      new.league_id;
  end if;

  if league_sport_key <> 'bracket_challenge' then
    raise exception
      'Bracket entry league % must use sport_key bracket_challenge, found %',
      new.league_id,
      league_sport_key;
  end if;

  return new;
end;
$$;

drop trigger if exists
  bracket_entries_validate_league
on public.bracket_entries;

create trigger bracket_entries_validate_league
before insert or update of league_id
on public.bracket_entries
for each row
execute function public.validate_bracket_entry_league();


-- ============================================================
-- 8. GROUP COMPETITIVE-HISTORY PROTECTION
--
-- Bracket entries are competitive history just like slates,
-- NCAA Pick'em weeks, NBA Skins seasons, and League awards.
--
-- Keep the existing safe-empty-Group behavior, adding bracket
-- entries to the history guard so deletion fails intentionally
-- with the normal competitive-history message.
-- ============================================================

create or replace function public.delete_empty_group(
  target_group_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_group public.groups%rowtype;
begin
  select *
  into target_group
  from public.groups
  where id = target_group_id
  for update;

  if not found then
    raise exception 'Group not found.';
  end if;

  if target_group.slug = '111' then
    raise exception 'The primary 111 Group cannot be deleted.';
  end if;

  if target_group.is_active then
    raise exception 'Deactivate the Group before permanently deleting it.';
  end if;

  if exists (
    select 1
    from public.leagues league
    join public.slates slate on slate.league_id = league.id
    where league.group_id = target_group_id
  ) or exists (
    select 1
    from public.leagues league
    join public.ncaa_pickem_weeks week on week.league_id = league.id
    where league.group_id = target_group_id
  ) or exists (
    select 1
    from public.leagues league
    join public.nba_skins_seasons season on season.league_id = league.id
    where league.group_id = target_group_id
  ) or exists (
    select 1
    from public.leagues league
    join public.league_awards award on award.league_id = league.id
    where league.group_id = target_group_id
  ) or exists (
    select 1
    from public.leagues league
    join public.bracket_entries entry on entry.league_id = league.id
    where league.group_id = target_group_id
  ) then
    raise exception
      'This Group has competitive history and cannot be permanently deleted.';
  end if;

  delete from public.leagues
  where group_id = target_group_id;

  delete from public.teams
  where group_id = target_group_id;

  delete from public.groups
  where id = target_group_id;
end;
$$;


-- ============================================================
-- 9. ROW LEVEL SECURITY
--
-- Bracket Challenge runtime access will be server-mediated using
-- the existing 111 Sports auth + League -> Group authorization
-- pattern.
--
-- No permissive client policies are introduced here.
-- ============================================================

alter table public.bracket_competitions
  enable row level security;

alter table public.bracket_games
  enable row level security;

alter table public.bracket_entrants
  enable row level security;

alter table public.bracket_entries
  enable row level security;

alter table public.bracket_picks
  enable row level security;


-- ============================================================
-- 10. COMMENTS
-- ============================================================

comment on table public.bracket_competitions is
  'Real-world bracket competitions shared across Groups, such as CFP, NCAA tournaments, and future playoff brackets.';

comment on table public.bracket_games is
  'Directed tournament graph nodes belonging to a Bracket Challenge competition.';

comment on table public.bracket_entrants is
  'Bracket participant identities independent of fantasy teams and Group membership.';

comment on table public.bracket_entries is
  'League-owned Bracket Challenge participation with frozen rules and lock-time bracket snapshots.';

comment on table public.bracket_picks is
  'Normalized editable winner selections for Bracket Challenge entries.';


commit;
